file = open('exemplo.txt','a+')
file.write('Oi Chaves ;) \n')
file.write('Hola Casada ;) \n')
file.write('Hello Casada ;) \n')
file.seek(0,0)
print(file.read())
file.write("OI dnv \n")
file.seek(0,0)
file.close()